### ISSUE TITLE
Não sei pq está acontecendo esse erro

### ISSUE THREAD

**Issue by marcelokayata** [michelpf/fiap-ml-visao-computacional-capstone-alternative#1]
![duvida1](https://user-images.githubusercontent.com/25636975/79624822-d7dd3800-80fa-11ea-96ba-2de6c99dc3ce.PNG)
![duvida2](https://user-images.githubusercontent.com/25636975/79624823-d875ce80-80fa-11ea-8cf3-c733e69620e2.PNG)

**Comment by michelpf** [comment]
Geradores não retornam String. Não devem ser utilizados com o comando print.

**Comment by michelpf** [comment]
Você precisa entender bem as operações do _transfer learning_. Indico estudar esse 📙 [Notebook de transfer learning](https://github.com/michelpf/fiap-ml-visao-computacional/blob/master/aula-5-machine-learning-aplicado/transfer-learning-fruits.ipynb). Há poucas diferenças entre esse e o do projeto.
