### ISSUE TITLE
Dúvida treinamento dos pesos

### ISSUE THREAD

**Issue by marcelokayata** [michelpf/fiap-ml-visao-computacional-capstone-alternative#2]
ValueError: You are passing a target array of shape (32, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:
```
from keras.utils import to_categorical
y_binary = to_categorical(y_int)
```

Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.

A imagem:

![image](https://user-images.githubusercontent.com/25636975/82744824-f4047280-9d53-11ea-8ac0-06374693b325.png)

**Comment by marcelokayata** [comment]
![image](https://user-images.githubusercontent.com/25636975/82763033-f5c54900-9dda-11ea-9ac2-a45f73024f99.png)
Fiz o que ele pediu e ele falou que não possível:
![image](https://user-images.githubusercontent.com/25636975/82763052-0fff2700-9ddb-11ea-8d4d-d2d98cb11d1d.png)
MemoryError: Unable to allocate 9.19 MiB for an array with shape (16, 224, 224, 3) and data type float32

Um erro de memória

Aqui está o arquivo:

[analise-imagens-medicas.zip](https://github.com/michelpf/fiap-ml-visao-computacional-capstone-alternative/files/4674254/analise-imagens-medicas.zip)

**Comment by marcelokayata** [comment]
removi a parte to_categorical e da esse erro:
ValueError: Error when checking target: expected dense_2 to have shape (3,) but got array with shape (1,)

![image](https://user-images.githubusercontent.com/25636975/82764454-2d38f300-9de5-11ea-88d7-65489a4b98fe.png)

**Comment by michelpf** [comment]
Olá Marcelo, você precisa se basear neste [Notebook](https://github.com/michelpf/fiap-ml-visao-computacional/blob/master/aula-5-machine-learning-aplicado/transfer-learning-fruits.ipynb).

Veja que o que muda de um modelo, por exemplo que está nesta referência ```
conv_base = VGG16(include_top=False)``` para outro modelo é mudando essa classe, por exemplo ```conv_base = ResNet50(include_top=False)```, aqui a referência na [documentação](https://keras.io/api/applications/resnet/#resnet50-function).

O projeto segue a base da referência citada, revise cada parte dele.

Lembre-se também que o projeto é um caminho guiado. Você precisa completar aos poucos conforme é pedido, sempre que houver uma variável igual a ```None``` você precisa completar, nada a mais. Não tente fugir muito desse caminho, exceto se tiver um conhecimento muito profundo, do contrário poderá ir por caminhos das quais fogem até mesmo do que propus.

Fique atento que as imagens de validação são uma fração das de treino, logo o diretório que precisa estar na configura não é o "validation", mas sim o "training".
