### ISSUE TITLE
Dúvida layers, erro de dimensões

### ISSUE THREAD

**Issue by marcelokayata** [michelpf/fiap-ml-visao-computacional-capstone-alternative#3]
![image](https://user-images.githubusercontent.com/25636975/82934918-ab6ed400-9f62-11ea-9dd1-eab544ebde24.png)

Erro: Input 0 is incompatible with layer global_average_pooling2d_3: expected ndim=4, found ndim=2
Está igual ao de frutas, porém a parte do resnet, coloquei a versão nova e pelo que entendi, já subistitui a parte de layers, mas não entendi como faz para treinar, peguei o exemplo que passou do resnet: https://keras.io/api/applications/resnet/#resnet50-function.

Onde que eu posso procurar de como treinar algo novo? Procurei nessa documentação e não encontrei.

**Comment by michelpf** [comment]
Marcelo, o trecho do notebook não precisa nem alterar essa parte. Faz o seguinte, para termos certeza que vc está com o projeto original, faça um novo clone e comece do zero.

Essa parte da arquitetura não precisa alterar. Apenas no começo, onde você precisa baixar o dataset, descompactar e copiar as pastas dentro da pasta ```train```.

Depois disso defina o número de classes, no nosso caso são 2.

Use esse exemplo do _Fruits_ para comparar, ele é um pouco diferente pois mudamos as métricas de sucesso para fazer mais sentido com imagens médicas, do que classificação das frutas.

Que tal, começar de novo, faça essa sugestões, crie um repositório e a medida que você evolui, você atualiza e me compartilha ele?

Se for muito complicado, pode compartilhar um arquivo compactado mesmo.

Abraço.

**Comment by marcelokayata** [comment]
Deu certo
