### ISSUE TITLE
Dúvida Keras

### ISSUE THREAD

**Issue by marcelokayata** [michelpf/fiap-ml-visao-computacional-capstone-alternative#4]
O meu código já está rodando e fui pesquisar a documentação e o código está funcionando de uma maneira diferente da documentação, acredito que eu esteja vendo no lugar errado.
![image](https://user-images.githubusercontent.com/25636975/83298095-39002d00-a1ca-11ea-8bfa-a780487b7016.png)

O link da documentação: https://keras.io/api/layers/core_layers/dense/

O git do meu código: https://github.com/marcelokayata/desafio_visao/blob/master/analise-imagens-medicas.ipynb

Estou tentando mexer no Keras para aumentar o val_precision_score

**Comment by michelpf** [comment]
Marcelo, essa mensagem de warning ```UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.``` não interfere no andamento do projeto, não se preocupe. Eu fiz os testes e não encontrei nenhum problema.

É que o novo Keras foi incorporado para dentro do TensorFlow na última versão e precisamos atualizar mais para frente, mas não representa um problema para você.

Aproveitando, notei que você tinha indicado uma pasta diferente no gerador de validação. Não é assim, você precisa indicar a mesma pasta que tem os dados de treinamento mesmo, que o gerador de validação vai usar a porcentagem que você indicou. Ou seja, pode manter a pasta ```raiox```, note que ali eu nem peço para implementar nada.

Para ter certeza que está com as imagens corretas, note a mensagem que é exibida após os geradores serem executados, eles mostram quantas imagens foram carregadas (exemplo se for utilizado todo o dataset ```Found 3652 images belonging to 3 classes.```) para testes e também para validação (exemplo se for utilizado todo o dataset ```Found 1564 images belonging to 3 classes.```).

Dá uma olhada [aqui](https://github.com/michelpf/fiap-ml-visao-computacional-capstone-alternative/issues/5#issuecomment-636555421) que dou uma dica de como organizar as imagens de treinamento.

**Comment by marcelokayata** [comment]
Muito obrigado
