### ISSUE TITLE
Passo a Passo difícil de entender.

### ISSUE THREAD

**Issue by flavioldias2** [michelpf/fiap-ml-visao-computacional-capstone-alternative#5]
Boa noite, estou com grande dificuldade em entender os passos a serem seguidos e o que é esperado nas implementações. Acredito que esses exercícios deveriam ser explicados em sala de aula e não apenas em um arquivo a ser seguido.
Logo no começo já fica a dúvida de como prosseguir, conforme trecho abaixo:

"Para construir este classificador, utilize o dataset do Kaggle Chest Ray Pneumonia e organize os dados de forma a separar em cada uma das classes que já estão definidas no diretório raio-x, sendo controle para as imagens normais (sem inflamação), bactéria para as imagens de pneumonia bacteriana e viral para as imagens de pneumonia viral."

Dúvida - Quais caminhos e pastas devem ser criados? pois ao efetuar o download do projeto as pastas estão vazias, sem identificação de imagens e locais onde salvar, diferentemente do projeto de auditoria de vídeo, o qual já possui as imagens e pastas definidas.

Critica construtiva - Esses trabalhos deveriam ser mais explorados em sala de aula, o aluno fica sem saber o que fazer ao apenas ler um documento, situação que piora quando o processo de solução de dúvidas fica restrito a uma ferramenta que poucos tem familiaridade.

Obrigado.

**Comment by michelpf** [comment]
Olá Flavio,

Fizemos um projeto como este em sala de aula. Ao invés de usarmos imagens de raio-x utilizamos o dataset de frutas. Aqui está o [notebook](https://github.com/michelpf/fiap-ml-visao-computacional/blob/master/aula-5-machine-learning-aplicado/transfer-learning-fruits.ipynb) que trabalhamos.

Conforme vimos em aula, o nome das classes de cada grupo de imagens é o próprio diretório. Portanto neste caso em específico você deve ter notado que a pasta ```raiox``` está vazia pois o dataset é bem grande e por isso que foi solicitado para baixar o dataset do site do Kaggle, diretamente.

Você vai no link indicado, baixe o arquivo de dataset que está compactado. Depois de descompactar, vai ver que tem 3 diretórios, mas no nosso caso, somente a pasta ```train``` é a que precisamos.

Dentro da pasta ```train``` tem a pasta ```NORMAL``` (dados de controle, sujeitos saudáveis)  e ```PNEUMONIA``` (nesta pasta tem imagens de sujeitos com pneumonia do tipo bacteriana e viral).  

Na pasta ```PNEUMONIA``` como tem os 2 tipos (viral e bacteriana) juntos, você precisa separar em outros 2 diretórios, podendo ser, por referência, ```PNEUMONIA_BACTERIANA```  e ```PNEUMONIA_VIRAL```. O sufixo das imagens indicam qual é o tipo de pneumonia. Por exemplo, o exame de raio-x da imagem ```person74_bacteria_362.jpeg``` indica que é pneumonia do tipo bacteriana e o raio-x da imagem ```person80_virus_150.jpeg``` indica que é do tipo viral.

Com os 3 diretórios, ```NORMAL```, ```PNEUMONIA_BACTERIANA```  e ```PNEUMONIA_VIRAL```, copie eles para dentro do diretório ```raiox```.

Acredito que os próximos passos você deva conseguir caminhar.

Qualquer dificuldade estou a disposição. 

Um abraço.
