### ISSUE TITLE
Subir imagens no github

### ISSUE THREAD

**Issue by marcelokayata** [michelpf/fiap-ml-visao-computacional-capstone-alternative#6]
Te fiz um convite no github, pois deixei privado;

![image](https://user-images.githubusercontent.com/25636975/83696942-160fb780-a5d4-11ea-994e-1d177bdaee5f.png)

Tenho que subir as imagens também ou só o código?

**Comment by flavioldias2** [comment]
Professor, fiz o mesmo que o Marcelo, te enviei um convite para Colaborar e ter acesso ao Git criado.

As imagens de treinamento/validação não foram disponibilizadas no Git, vez que não aceita a quantidade de arquivos.
As imagens de ilustração das arquiteturas funcionaram normalmente no PC, porém no Git não esta aparecendo. Caso fique com dúvidas, as imagens estão na pasta projeto-final/imagens.

Obrigado.

**Comment by michelpf** [comment]
Obrigado, mas os repos precisam estarem públicos. Serão parte do portfólio de vocês.
