### ISSUE TITLE
Dúvida Simples

### ISSUE THREAD

**Issue by flavioldias2** [michelpf/fiap-ml-visao-computacional-capstone-alternative#7]
Bom dia Professor,
Tenho uma dúvida simples.
No Trecho "Escolha o número adequado de épocas para alcançarmos pelo menos 70% de precisão de validação." você se refere a qual campo: **precision_score** ou **val_precision_score**?

O exemplo abaixo estaria dentro ou fora da regra solicitada?
loss: 0.5491 - precision_score: 0.8256 - recall_score: 0.7437 - f1_score: 0.7802 - val_loss: 1.4294 - val_precision_score: 0.3760 - val_recall_score: 0.3688 - val_f1_score: 0.3723

Obrigado!

**Comment by michelpf** [comment]
É do ```val_precision_score```.  Veja que a avaliação do modelo sempre é do conjunto de dados de validação.
Veja se você, no começo do projeto, utilizou as imagens corretas de treinamento. Dá uma olhada [nisso](https://github.com/michelpf/fiap-ml-visao-computacional-capstone-alternative/issues/5#issuecomment-636555421).

**Comment by flavioldias2** [comment]
Segui o passo a passo informado e utilizei 1000 imagens de cada classe, não sei se deu esse resultado pelo baixo números de épocas que usei para exemplificar aqui...
Fiz com 10 épocas no RESNet50 e deu o resultado abaixo:

Epoch 1/10
5/5 [==============================] - 66s 13s/step - loss: 1.2541 - precision_score: 0.5094 - recall_score: 0.3500 - f1_score: 0.4118 - val_loss: 1.2395 - val_precision_score: 0.5220 - val_recall_score: 0.4187 - val_f1_score: 0.4640
Epoch 2/10
5/5 [==============================] - 53s 11s/step - loss: 0.6064 - precision_score: 0.8314 - recall_score: 0.7000 - f1_score: 0.7582 - val_loss: 1.1716 - val_precision_score: 0.5663 - val_recall_score: 0.5437 - val_f1_score: 0.5546
Epoch 3/10
5/5 [==============================] - 52s 10s/step - loss: 0.6237 - precision_score: 0.7865 - recall_score: 0.7250 - f1_score: 0.7530 - val_loss: 1.5537 - val_precision_score: 0.4722 - val_recall_score: 0.4688 - val_f1_score: 0.4704
Epoch 4/10
5/5 [==============================] - 50s 10s/step - loss: 0.6493 - precision_score: 0.7540 - recall_score: 0.6812 - f1_score: 0.7152 - val_loss: 1.1964 - val_precision_score: 0.4534 - val_recall_score: 0.3938 - val_f1_score: 0.4211
Epoch 5/10
5/5 [==============================] - 49s 10s/step - loss: 0.6879 - precision_score: 0.7466 - recall_score: 0.7125 - f1_score: 0.7289 - val_loss: 1.0533 - val_precision_score: 0.5644 - val_recall_score: 0.5000 - val_f1_score: 0.5302
Epoch 6/10
5/5 [==============================] - 48s 10s/step - loss: 0.5937 - precision_score: 0.7669 - recall_score: 0.7437 - f1_score: 0.7550 - val_loss: 0.9040 - val_precision_score: 0.6185 - val_recall_score: 0.5750 - val_f1_score: 0.5956
Epoch 7/10
5/5 [==============================] - 53s 11s/step - loss: 0.5381 - precision_score: 0.8283 - recall_score: 0.7850 - f1_score: 0.8059 - val_loss: 1.2338 - val_precision_score: 0.4542 - val_recall_score: 0.4125 - val_f1_score: 0.4322
Epoch 8/10
5/5 [==============================] - 53s 11s/step - loss: 0.4853 - precision_score: 0.8238 - recall_score: 0.7812 - f1_score: 0.8014 - val_loss: 1.3270 - val_precision_score: 0.4238 - val_recall_score: 0.3875 - val_f1_score: 0.4046
Epoch 9/10
5/5 [==============================] - 53s 11s/step - loss: 0.5314 - precision_score: 0.7798 - recall_score: 0.7500 - f1_score: 0.7646 - val_loss: 0.6813 - val_precision_score: 0.7529 - val_recall_score: 0.6625 - val_f1_score: 0.7047
Epoch 10/10
5/5 [==============================] - 52s 10s/step - loss: 0.5470 - precision_score: 0.8429 - recall_score: 0.8313 - f1_score: 0.8369 - val_loss: 0.5832 - val_precision_score: 0.7205 - val_recall_score: 0.6375 - val_f1_score: 0.6756

Será que tem algo errado? Fiquei na dúvida agora...rs

**Comment by michelpf** [comment]
Não está não. Vai ver que dependendo da arquitetura utilizada uns vão ter um desempenho melhor do que outros.
Você está no caminho certo e 10 épocas está ótimo!

**Comment by flavioldias2** [comment]
Obrigado!!
