### ISSUE TITLE
Posso usar a pasta de teste para a validação?

### ISSUE THREAD

**Issue by hgf777-br** [michelpf/fiap-ml-visao-computacional-capstone-alternative#8]
Gostaria de usar a pasta de teste do conjunto de dados para a validação. 

Minha ideia é aprimorar (augment) as imagens de treino, mas não queria mexer nas de validação. E com o Keras fazendo a divisão isso não é possível.

Posso usar a base de teste para validar então?

**Comment by michelpf** [comment]
Pode sim, não há problemas!
